name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Build project
        run: npm run build

      - name: Install Deno
        use: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Deno Deploy CLI
        run: deno install --allow-read --allow-write --allow-env --allow-net --allow-run --no-check -r -f https://deno.land/x/deploy/deployctl.ts

      - name: Deploy to Deno
        run: deployctl deploy --project=benpops89-remix-deno --include=.cache,build,public ./build/index.js
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
